# Generated by Django 4.0.4 on 2022-05-20 09:18

from django.db import migrations, models
import django.db.models.deletion
import polls.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TradePointType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, validators=[polls.validators.validate_empty_string])),
            ],
        ),
        migrations.CreateModel(
            name='TradePoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('point_size', models.IntegerField(null=True, validators=[polls.validators.validate_gt_0])),
                ('rent_payment', models.IntegerField(null=True, validators=[polls.validators.validate_gt_0])),
                ('utilities_payment', models.IntegerField(null=True, validators=[polls.validators.validate_gt_0])),
                ('point_counter_amount', models.IntegerField(null=True, validators=[polls.validators.validate_gt_0])),
                ('point_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='polls.tradepointtype')),
            ],
        ),
    ]
