# Generated by Django 4.0.4 on 2022-05-20 20:16

from django.db import migrations, models
import django.db.models.deletion
import polls.validators


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, validators=[polls.validators.validate_empty_string])),
                ('info', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DepartmentStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Distributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.CharField(max_length=255, validators=[polls.validators.validate_empty_string])),
                ('rating', models.IntegerField(validators=[polls.validators.validate_gte_0])),
            ],
        ),
        migrations.CreateModel(
            name='DistributorProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(validators=[polls.validators.validate_gt_0])),
                ('offer_is_active', models.BooleanField()),
                ('offer_start_date', models.DateField()),
                ('distributor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.distributor')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, validators=[polls.validators.validate_empty_string])),
                ('salary', models.IntegerField(validators=[polls.validators.validate_gt_0])),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, validators=[polls.validators.validate_empty_string])),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductsOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='polls.customer')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='polls.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='SomeStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='tradepoint',
            name='name',
            field=models.CharField(max_length=255, validators=[polls.validators.validate_empty_string]),
        ),
        migrations.AlterField(
            model_name='tradepoint',
            name='point_counter_amount',
            field=models.IntegerField(blank=True, null=True, validators=[polls.validators.validate_gt_0]),
        ),
        migrations.AlterField(
            model_name='tradepoint',
            name='point_size',
            field=models.IntegerField(blank=True, null=True, validators=[polls.validators.validate_gt_0]),
        ),
        migrations.AlterField(
            model_name='tradepoint',
            name='rent_payment',
            field=models.IntegerField(blank=True, null=True, validators=[polls.validators.validate_gt_0]),
        ),
        migrations.AlterField(
            model_name='tradepoint',
            name='utilities_payment',
            field=models.IntegerField(blank=True, null=True, validators=[polls.validators.validate_gt_0]),
        ),
        migrations.CreateModel(
            name='ProductOrderItem',
            fields=[
                ('products_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='polls.productsorder')),
                ('price', models.IntegerField(validators=[polls.validators.validate_gt_0])),
                ('amount', models.IntegerField(validators=[polls.validators.validate_gt_0])),
            ],
        ),
        migrations.CreateModel(
            name='ReceiptItem',
            fields=[
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='polls.receipt')),
                ('amount', models.IntegerField(validators=[polls.validators.validate_gt_0])),
                ('price', models.IntegerField(validators=[polls.validators.validate_gt_0])),
            ],
        ),
        migrations.CreateModel(
            name='RequestItem',
            fields=[
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='polls.request')),
                ('amount', models.IntegerField(validators=[polls.validators.validate_gt_0])),
            ],
        ),
        migrations.CreateModel(
            name='RequestOrder',
            fields=[
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='polls.request')),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.somestore')),
            ],
        ),
        migrations.AddField(
            model_name='somestore',
            name='trade_point',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.tradepoint'),
        ),
        migrations.CreateModel(
            name='SoldProduct',
            fields=[
                ('trade_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='polls.tradepoint')),
                ('price', models.IntegerField(validators=[polls.validators.validate_gt_0])),
                ('in_stock', models.IntegerField(validators=[polls.validators.validate_gte_0])),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.product')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_number', models.IntegerField(validators=[polls.validators.validate_gt_0])),
                ('floor', models.IntegerField(validators=[polls.validators.validate_gte_0])),
                ('section_manager', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='polls.employee')),
                ('trade_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.departmentstore')),
            ],
        ),
        migrations.AddField(
            model_name='request',
            name='request_item',
            field=models.ManyToManyField(related_name='request_items', through='polls.RequestItem', to='polls.product'),
        ),
        migrations.AddField(
            model_name='request',
            name='trade_point',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.tradepoint'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='receipt_item',
            field=models.ManyToManyField(related_name='receipt_items', through='polls.ReceiptItem', to='polls.product'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='trade_point',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='polls.tradepoint'),
        ),
        migrations.AddField(
            model_name='productsorder',
            name='product_order_item',
            field=models.ManyToManyField(related_name='product_order_items', through='polls.ProductOrderItem', to='polls.distributorproduct'),
        ),
        migrations.AddField(
            model_name='productsorder',
            name='request_order',
            field=models.ManyToManyField(related_name='request_orders', through='polls.RequestOrder', to='polls.request'),
        ),
        migrations.AddField(
            model_name='product',
            name='sold_product',
            field=models.ManyToManyField(related_name='sold_products', through='polls.SoldProduct', to='polls.tradepoint'),
        ),
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hall_number', models.IntegerField(validators=[polls.validators.validate_gt_0])),
                ('employees_number', models.IntegerField(blank=True, null=True, validators=[polls.validators.validate_gte_0])),
                ('trade_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.somestore')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='working_point',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='polls.tradepoint'),
        ),
        migrations.AddField(
            model_name='distributorproduct',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.product'),
        ),
        migrations.AddField(
            model_name='distributor',
            name='distributor_product',
            field=models.ManyToManyField(related_name='distributor_products', through='polls.DistributorProduct', to='polls.product'),
        ),
        migrations.AddField(
            model_name='departmentstore',
            name='trade_point',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.somestore'),
        ),
        migrations.AddConstraint(
            model_name='soldproduct',
            constraint=models.UniqueConstraint(fields=('trade_point', 'product_id'), name='unique_trade_point_id_product_id'),
        ),
        migrations.AddConstraint(
            model_name='section',
            constraint=models.UniqueConstraint(fields=('section_number', 'trade_point'), name='unique_section_number_trade_point'),
        ),
        migrations.AddField(
            model_name='requestorder',
            name='order_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.productsorder'),
        ),
        migrations.AddField(
            model_name='requestitem',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.product'),
        ),
        migrations.AddField(
            model_name='receiptitem',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='polls.product'),
        ),
        migrations.AddField(
            model_name='productorderitem',
            name='distributor_product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.distributorproduct'),
        ),
        migrations.AddConstraint(
            model_name='hall',
            constraint=models.UniqueConstraint(fields=('hall_number', 'trade_point'), name='unique_hall_number_trade_point'),
        ),
        migrations.AddConstraint(
            model_name='requestorder',
            constraint=models.UniqueConstraint(fields=('request', 'order_id'), name='unique_request_id_distributor_order_id'),
        ),
        migrations.AddConstraint(
            model_name='requestitem',
            constraint=models.UniqueConstraint(fields=('request', 'product_id'), name='unique_request_id_product_id'),
        ),
        migrations.AddConstraint(
            model_name='receiptitem',
            constraint=models.UniqueConstraint(fields=('receipt', 'product_id'), name='unique_receiptid_productid'),
        ),
        migrations.AddConstraint(
            model_name='productorderitem',
            constraint=models.UniqueConstraint(fields=('products_order', 'distributor_product_id'), name='unique_products_order_id_distributor_product_id'),
        ),
    ]
