# Generated by Django 4.0.4 on 2022-05-22 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_remove_requestitem_unique_request_id_product_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='distributorproduct',
            old_name='distributor_id',
            new_name='distributor',
        ),
        migrations.RenameField(
            model_name='distributorproduct',
            old_name='product_id',
            new_name='product',
        ),
    ]
