# Generated by Django 4.0.4 on 2022-05-26 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_rename_distributor_id_distributorproduct_distributor_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='productorderitem',
            name='unique_products_order_id_distributor_product_id',
        ),
        migrations.RemoveConstraint(
            model_name='requestorder',
            name='unique_request_id_distributor_order_id',
        ),
        migrations.RenameField(
            model_name='productorderitem',
            old_name='distributor_product_id',
            new_name='distributor_product',
        ),
        migrations.RenameField(
            model_name='requestorder',
            old_name='order_id',
            new_name='order',
        ),
        migrations.AddConstraint(
            model_name='productorderitem',
            constraint=models.UniqueConstraint(fields=('products_order', 'distributor_product'), name='unique_products_order_id_distributor_product_id'),
        ),
        migrations.AddConstraint(
            model_name='requestorder',
            constraint=models.UniqueConstraint(fields=('request', 'order'), name='unique_request_id_distributor_order_id'),
        ),
    ]
